HomeTask_09
YrShavlak/Education pull request #8
Opened 2023-07-07 11:22 UTC by YrShavlak

2023-07-08 07:10 UTC, antohaUa requested changes

2023-07-08 07:10 UTC, antohaUa commented on Test_1/HomeTask_09.py
> +    for position, letter in enumerate(english_alphabet, start=1):
We need to find real position in file NOT the index. For example q -> pos 26294.
Please change your algorithm. Pay attention that letters could be not unique. For example several "e" inside

2023-07-10 10:19 UTC, YrShavlak commented on Test_1/HomeTask_09.py
> +    for position, letter in enumerate(english_alphabet, start=1):
Updated new version of my code, please check

2023-07-10 10:39 UTC, antohaUa approved these changes

2023-07-10 10:39 UTC, antohaUa commented on Test_1/HomeTask_09.py
> +        english_letter.append((el, str(pos)))
```suggestion
english_letter = [(el, str(pos))
                  for pos, el in enumerate(input_text, start=1)
                  if re.search('[a-zA-Z]', el)]
```

Better organize  such patterns as list comprehensions. Also do not forget that "if" will do bool for you automatically

2023-07-10 10:39 UTC, antohaUa commented on Test_1/HomeTask_09.py
> +for pos, el in enumerate(input_text, start=1):
You see check each element with regexp is not optimized solution. This could be for large files too time consuming.
So better to search through the whole text. For example `re.finditer` is one possible option

2023-07-13 11:11 UTC, merged